import "./globals.css"; // ✅ ¡esto es obligatorio!
import { Lora } from "next/font/google";


const lora = Lora({
  weight: '400',
  subsets: ['latin']
});


/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={lora.className}> 
      <body>{children}</body>
    </html>
  );
}

