import "./globals.css"; // ✅ ¡esto es obligatorio!
import { Yeseva_One } from "next/font/google";


const yesevaOne = Yeseva_One({
  weight: '400',
  subsets: ['latin']
});


/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

